# Generated by Django 3.2.9 on 2021-11-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(default='', max_length=2)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Age', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('DOJ', models.TextField(default='')),
                ('Salary', models.IntegerField(default='')),
            ],
        ),
    ]
